icodewhatithink/urls.py
from django.urls import path

from . import views

app_name = 'icodewhatithink'
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('<slug:slug>/', views.PostDetailView.as_view(), name="post_detail"),
]

marc_lin/urls.py
from decouple import config
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView

admin.site.site_header = "Marc Lin Administration"
admin.site.site_title = "Marc Lin admin"

urlpatterns = [
    path(
        "admin/password_reset/",
        auth_views.PasswordResetView.as_view(),
        name="admin_password_reset",
    ),
    path(
        "admin/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("graphql/", csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path(f"{config('SECRET_ADMIN_URL')}/", admin.site.urls),
    path("", include("icodewhatithink.urls")),
    path("pirvacy_thinking", include("privacy_thinking.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

privacy_thinking/urls.py
from django.urls import path

from . import views

app_name = 'privacy_thinking'
urlpatterns = [
    path('', views.posts, name="posts"),
    # path('<slug:slug>/', views.PostDetailView.as_view(), name="post_detail"),
]

core/models.py
from django.db import models

# Create your models here.

icodewhatithink/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Tag(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class PostQuerySet(models.QuerySet):
    def showed(self):
        return self.filter(show=True).only("title", "slug")


class Post(models.Model):
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=256, null=True)
    author = models.CharField(max_length=256, default="Sentoz Lin")
    content = models.TextField()
    pub_datetime = models.DateTimeField(default=timezone.now)
    tags = models.ManyToManyField(Tag, blank=True, related_name="posts")
    show = models.BooleanField(default=True)

    objects = PostQuerySet.as_manager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("icodewhatithink:post_detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ("-pub_datetime",)

privacy_thinking/models.py
from django.db import models

# Create your models here.

core/views.py
# from django.shortcuts import render

# Create your views here.

icodewhatithink/views.py
from django.views import generic

from .models import Post


class HomeView(generic.ListView):
    model = Post
    queryset = Post.objects.showed()
    context_object_name = "posts"
    template_name = "icodewhatithink/home.html"


class PostDetailView(generic.DetailView):
    model = Post
    slug_field = "slug"
    template_name = "icodewhatithink/post.html"

privacy_thinking/views.py
from django.shortcuts import render
from django.template.response import TemplateResponse

# Create your views here.
def posts(request):
    return TemplateResponse(request, "privacy_thinking/posts.html")

icodewhatithink/templates/icodewhatithink/home.html
{% extends "base.html" %}
{% block content %}
{% for post in posts%}
<h2>
  <a href="{{post.get_absolute_url}}">
    {{post.title}}
  </a>
</h2>
{% if not forloop.last %}
<hr />
{% endif %}
{% endfor %}
{% endblock content %}

icodewhatithink/templates/icodewhatithink/post.html
{% extends "base.html" %}
{% load markdown_deux_tags %}

{% block title %}
| {{post.title}}
{% endblock title %}

{% block content %}
<h4>
  {{post.title}}
</h4>
<span>
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#d9d8dc"
    stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
    <rect x="3" y="4" width="18" height="18" rx="2" ry="2" />
    <line x1="16" y1="2" x2="16" y2="6" />
    <line x1="8" y1="2" x2="8" y2="6" />
    <line x1="3" y1="10" x2="21" y2="10" />
  </svg>
  {{post.pub_datetime|date:'r'}}
</span>

<span>
  <a href="/self/">
    &nbsp &nbsp
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#eb99a1"
      stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
      <path d="M20 14.66V20a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h5.34" />
      <polygon points="18 2 22 6 12 16 8 16 8 12 18 2" />
    </svg>
    {{post.author}}
  </a>
</span>
<hr>
{{post.content|markdown}}

{% endblock content %}

privacy_thinking/templates/privacy_thinking/posts.html
{% extends "base.html" %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>
      948794Crazy‼️‼️‼️ {% block title %} {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" 
          href="{% static "icodewhatithink/css/sakura-vader.css"%}"
          type="text/css">
    <link rel="stylesheet" 
          href="{% static "icodewhatithink/css/custom.css"%}"
          type="text/css" 
          media="screen"
          title="no title"
          charset="utf-8">
    <link rel="stylesheet" 
          href="{% static "header.css"%}"
          type="text/css" 
          media="screen"
          title="no title"
          charset="utf-8">
    <script
      defer
      src="{% static 'icodewhatithink/3rd_party_js/ztext.min.js' %}"
    ></script>
  </head>

  <body>
    <div class="container">
      {% include 'partials/header.html' %}
      <main>
        {% include 'partials/messages.html' %}
        {% block content %} {% endblock %}
      </main>
      {% include 'partials/footer.html' %}
    </div>

    {% block extend_footer %} {% endblock extend_footer %}
  </body>
</html>

templates/partials/footer.html
<footer>
  <hr />
  <p>
    Built with 💖 by <a href="/self/">SentozLin.</a>
    <a href="http://rhrpmc5sd2fjtr3fb5gj6uowbtk4qxva6byaclhaedfiatrwbfj7xyid.onion/">
    🧅
    </a>
    <br />
    <small>
        Copyright&nbsp;&copy;&nbsp;2017-{% now 'Y' %} <i>948794Crazy</i>
    </small>
    .&nbsp;&nbsp;All rights reserved.
    <br>
  </p>
</footer>

templates/partials/header.html
{% load flatpages %} {% get_flatpages as flatpages %}
<nav>
  <div>
    <div>
      <h1 data-z data-z-layers="1" data-z-depth="0.7em">
        <a href="/"><i>948794Crazy‼️‼️‼️</i></a>
        <br />
      </h1>
      <div class="header">
        {% for page in flatpages %}
        <a href="{{ page.url }}">
          {% if page.title == "Self" %}
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="#eb99a1"
            stroke-width="3"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <circle cx="12" cy="12" r="10" />
            <line x1="12" y1="16" x2="12" y2="12" />
            <line x1="12" y1="8" x2="12" y2="8" />
          </svg>
          {% endif %} {{ page.title }}
        </a>
        {% endfor %}
        <a href="{% url 'privacy_thinking:posts' %}">隱。思</a>
      </div>
      <hr />
    </div>
  </div>
</nav>

templates/partials/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}